### ISSUE TITLE
site with some SDRAM controller 

### ISSUE THREAD

**Issue by goran-mahovlic** [f32c/f32c#17]
http://codehackcreate.com/archives/444

**Comment by emard** [comment]
Thanks for pointing it out!

We should have taken a closer look at this controller and also 
the one from TG68K.
Now we have fitted hamsterworks sdram controler.
Above controllers might work too, but they are 16-bit and need
to be fitted for 32-bit access, while hamsterwork's had it already.

For F32C to utilize full bandwidth of SDRAM data burst streaming,
a clean rewrite will be the best.
