### ISSUE TITLE
lattice FX2 (ULX2S) textmode not fully functional

### ISSUE THREAD

**Issue by emard** [f32c/f32c#39]
when ULX2S is running at 81.25 MHz

In the textmode soft scroll example, corruption occurs
in the font 8-bit BRAM

pixels slowly change without reason 
(even with bram write signal disabled)
Workaround is to run at lower clock e.g. 50 MHz

textmode bitmap doesn't work at all.
(thus for ulx2s disabled)

vgahdmi bitmap works, this is "workaround"
if bitmap is required then disable vgatext and
use vgahdmi

if both bitmap and textmode should appear on
the same time on ulx2s then we currently have 
no workaround

**Comment by emard** [comment]
Bitmap "solution"

There was degenerate if comparison
std_logic_vector(-1 downto 0)  = std_logic_vector(-1 downto 0)
on xilinx holds true but on lattice is false
one OR fixed it.

It shows bitmap but textmode still won't
go faster than 50 MHz and there's no
enough memory bandwidth for 8bpp bitmap
so betmap although now is shown, is split
apart due to low bandwidth

**Comment by XarkLabs** [comment]
Hmm, XO2 has trouble > 50Mhz also so not all that surprising perhaps.

**Comment by emard** [comment]
One thing is strange, I use vgahdmi with bitmap only
and change clock
81.25MHz works
75MHz doesn't work (can't upload)
62MHz doesn't work (can't upload)
50MHz works but screen garbled (low bandwidth)

**Comment by emard** [comment]
Due to complexity of vga textmode, 50MHz is fmax on lattice FX2
