### ISSUE TITLE
src/examples won't compile

### ISSUE THREAD

**Issue by emard** [f32c/f32c#77]
src/tools$ . ./makefiles.sh 
*** Setting environment for f32c make ***

hello_c$ make
mips-elf-gcc -march=f32c -EL -G 32768 -Os -fpeel-loops -ffreestanding -c -pipe -ffunction-sections -fdata-sections -Wall -Werror  -nostdinc -include sys/param.h -I/home/guest/src/fpga/fpgarduino/f32c/src/tools/../include -o obj/mipsel/hello.o hello.c
mips-elf-ld -N -EL --section-start=.init=0x80000000 --library-path=/home/guest/src/fpga/fpgarduino/f32c/src/tools/../lib/mipsel -lcrt0 -gc-sections  -o hello  ./obj/mipsel/hello.o   -lcint
mips-elf-ld: cannot find -lcrt0
mips-elf-ld: cannot find -lcint
/home/guest/src/fpga/fpgarduino/f32c/src/tools/../conf/post.mk:240: recipe for target 'hello' failed
make: *** [hello] Error 1

**Comment by emard** [comment]
this is because f32c libraries are no longer distributed in binary form
and should be compiled from source

**Comment by exstob** [comment]
I try to compile example in folder "sdcard" and get next error:


user@server /c/MinGW/msys/1.0/home/uskov.o/f32c/src/examples/sdcard
$ make
riscv32-elf-ld -N -EL --section-start=.init=0x00000400 --library-path=/c/MinGW/msys/1.0/home/uskov.o/f32c/src/lib/riscv -gc-sections  -o sdtest ./obj/riscv/../../lib/src/riscv/start.O ./obj/riscv/sdcard_test.o ./obj/riscv/../../lib/src/sio_poll.o ./obj/riscv/../../lib/src/printf.o ./obj/riscv/../../lib/src/fatfs.o ./obj/riscv/../../lib/src/file.o ./obj/riscv/../../lib/src/malloc.o ./obj/riscv/../../lib/src/spi.o ./obj/riscv/../../lib/src/sdcard.o ./obj/riscv/../../lib/src/diskio.o ./obj/riscv/../../lib/src/mul.o ./obj/riscv/../../lib/src/div.o
./obj/riscv/../../lib/src/printf.o: In function `.L82':
printf.c:(.text._xvprintf+0x4b0): undefined reference to `__umoddi3'
printf.c:(.text._xvprintf+0x4dc): undefined reference to `__udivdi3'
make: *** [sdtest] Error 1


As I understand, this error for a reason using type uint64_t in file "div64.c", but how fix it?

**Comment by exstob** [comment]
I solved this problem. Need simply add path to "div64.c " in Makefile.

**Comment by goran-mahovlic** [comment]
Solution for:


```
mips-elf-ld: cannot find -lcrt0
mips-elf-ld: cannot find -lcint
```

https://github.com/f32c/f32c/issues/68#issuecomment-287402183

```
$ cd <path-to>/f32c/src/lib/src
$ make all_libs
```

So we can close it...

**Comment by goran-mahovlic** [comment]
Solution for:


```
mips-elf-ld: cannot find -lcrt0
mips-elf-ld: cannot find -lcint
```

https://github.com/f32c/f32c/issues/68#issuecomment-287402183

```
$ cd <path-to>/f32c/src/lib/src
$ make all_libs
```

So we can close it...
