### ISSUE TITLE
Incompatible changes to RISC-V ISA in f32c?

### ISSUE THREAD

**Issue by MayaPosch** [f32c/f32c#89]
This recent blog article describes how the RISC-V ISA in f32c uses absolute addressing: http://antti-brain.blogspot.com/2018/10/risc-v-take-i.html

Is this correct? If so, are there any plans to make the RISC-V ISA in f32c compatible with the standard?

**Comment by emard** [comment]
HI

gcc for f32c is absolutely the same as for all other risc-v, for
our RISCV ISA we don't apply any patch to gcc (as we do it for MIPS ISA)

RISC-V ISA has both absolute and relative jumps.  Relative jump
is usually slower for 1 cycle therefore compiler prefers absolute
jump. 

In http://antti-brain.blogspot.com/2018/10/risc-v-take-i.html
Antti wrote in assembler the command "j" (jump) so he got what he
asked for: absolute jump.  If he had written "b" (branch), he would
get relative jump, or unconditional  branch so I suggest to try it.

I think it should not be related to our ISA if some gcc-a / binutils
automatically converts "j" to "b"
